### PR TITLE
improvements

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]
Is the idea behind these improvements to be able to run this project independently from the `generate_licenses.sh` ? I recall I was struggling with it awhile back

**Comment by Ladicek** [comment]
It's mostly version updates, renaming to Thorntail and usage simplification. Running it standalone was always possible, but it's now a bit easier.

**Comment by sberyozkin** [comment]
Sounds good

**Comment by Ladicek** [comment]
Ah also the README is now up to date. It was very outdated, which might be why you struggled with running it standalone.

**Pull request merged**
